export { default as HomeHeroSection } from "./home/hero-section"
export { default as ExperienceSection } from "./home/experiences"
export { default as Services } from "./services"
export { default as Testimonials } from "./testimonials"
export { default as UsedTools } from "./UsedTools"
export { default as Stats } from "./Stats"
export { default as Cta } from "./callToAction"